export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const ADD_TO_WATCHLATER = 'ADD_TO_WATCHLATER';
export const REMOVE_FROM_WATCHLATER = 'REMOVE_FROM_WATCHLATER';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const LOGOUT = 'LOGOUT';

export const ADD_EPISODES = 'ADD_EPISODES';
export const REMOVE_EPISODES = 'REMOVE_EPISODES';
export const SET_AS_CURRENT_EPISODE = 'SET_AS_CURRENT_EPISODE';
export const SET_AS_PREVIOUS_EPISODE = 'SET_AS_PREVIOUS_EPISODE';
export const SET_AS_NEXT_EPISODE = 'SET_AS_NEXT_EPISODE';

export const PERSIST_APPUPDATE_NOTIF = 'PERSIST_APPUPDATE_NOTIF';
export const PERSIST_NEW_CONTENT_NOTIF = 'PERSIST_NEW_CONTENT_NOTIF';
export const PERSIST_NEW_FEATURE_NOTIF = 'PERSIST_NEW_FEATURE_NOTIF';
