export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const ADD_TO_WATCHLATER = 'ADD_TO_WATCHLATER';
export const REMOVE_FROM_WATCHLATER = 'REMOVE_FROM_WATCHLATER';
export const UPDATE_CURRENT_EPISODE = 'UPDATE_CURRENT_EPISODE';
export const UPDATE_NEXT_EPISODE = 'UPDATE_NEXT_EPISODE';
export const UPDATE_ALL_EPISODES = 'UPDATE_ALL_EPISODES';
export const REMOVE_ALL_EPISODES = 'REMOVE_ALL_EPISODES';