export const dummyData = [
    { id: 1, title: 'attack on titan'},
    { id: 2, title: 'jujutsu kaisen'},
    { id: 3, title: 'robinhood'},
    { id: 4, title: 'bungo stray dogs'},
    { id: 5, title: 'kimetsu no yaiba'},
    { id: 6, title: 'vinland saga'},
    { id: 7, title: 'attack on titan'},
    { id: 8, title: 'jujutsu kaisen'},
    { id: 9, title: 'robinhood'},
    { id: 10, title: 'bungo stray dogs'},
    { id: 11, title: 'kimetsu no yaiba'},
    { id: 12, title: 'vinland saga'},
    { id: 21, title: 'attack on titan'},
    { id: 23, title: 'jujutsu kaisen'},
    { id: 33, title: 'robinhood'},
    { id: 421, title: 'bungo stray dogs'},
    { id: 53, title: 'kimetsu no yaiba'},
    { id: 326, title: 'vinland saga'},
    { id: 73, title: 'attack on titan'},
    { id: 832, title: 'jujutsu kaisen'},
    { id: 921, title: 'robinhood'},
    { id: 1032, title: 'bungo stray dogs'},
    { id: 1123, title: 'kimetsu no yaiba'},
    { id: 1221, title: 'vinland saga'},
];